begin;

create table if not exists public.listing_reports (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  reporter_id uuid not null references public.profiles(id) on delete cascade,
  reason text not null check (reason in ('counterfeit', 'misleading', 'prohibited', 'stolen', 'spam', 'other')),
  details text not null default '' check (length(details) <= 2000),
  status text not null default 'open' check (status in ('open', 'reviewing', 'resolved', 'dismissed')),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz,
  unique (listing_id, reporter_id)
);

create table if not exists public.shipments (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null unique references public.orders(id) on delete cascade,
  method text not null check (method in ('courier_standard', 'courier_express', 'personal_pickup')),
  carrier text,
  tracking_number text,
  status text not null default 'preparing' check (status in ('preparing', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'delivery_failed', 'cancelled')),
  estimated_delivery_at timestamptz,
  shipped_at timestamptz,
  delivered_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.shipment_events (
  id bigint generated by default as identity primary key,
  shipment_id uuid not null references public.shipments(id) on delete cascade,
  status text not null,
  location text,
  note text not null default '',
  occurred_at timestamptz not null default now()
);

create table if not exists public.delivery_confirmations (
  order_id uuid primary key references public.orders(id) on delete cascade,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  condition_matches boolean not null,
  note text not null default '' check (length(note) <= 1000),
  confirmed_at timestamptz not null default now()
);

create table if not exists public.listing_boosts (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  tier text not null check (tier in ('top_24h', 'urgent_3d', 'homepage_7d')),
  amount numeric(10,2) not null check (amount >= 0),
  currency text not null default 'EUR' check (currency = 'EUR'),
  status text not null default 'pending' check (status in ('pending', 'active', 'expired', 'cancelled')),
  starts_at timestamptz,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  constraint listing_boost_dates check (expires_at is null or starts_at is null or expires_at > starts_at)
);

create index if not exists listing_reports_status_idx on public.listing_reports (status, created_at desc);
create index if not exists shipment_events_shipment_idx on public.shipment_events (shipment_id, occurred_at);
create index if not exists listing_boosts_active_idx on public.listing_boosts (listing_id, expires_at desc) where status = 'active';
create unique index if not exists listing_boosts_one_active_idx on public.listing_boosts (listing_id) where status = 'active';

create trigger shipments_set_updated_at before update on public.shipments for each row execute function public.set_updated_at();

alter table public.listing_reports enable row level security;
alter table public.shipments enable row level security;
alter table public.shipment_events enable row level security;
alter table public.delivery_confirmations enable row level security;
alter table public.listing_boosts enable row level security;

create policy "Users create own reports" on public.listing_reports for insert to authenticated
  with check (reporter_id = (select auth.uid()));
create policy "Users read own reports" on public.listing_reports for select to authenticated
  using (reporter_id = (select auth.uid()));

create policy "Order parties read shipments" on public.shipments for select to authenticated
  using (exists (select 1 from public.orders o where o.id = order_id and (select auth.uid()) in (o.buyer_id, o.seller_id)));
create policy "Sellers create shipments" on public.shipments for insert to authenticated
  with check (exists (select 1 from public.orders o where o.id = order_id and o.seller_id = (select auth.uid())));
create policy "Sellers update shipments" on public.shipments for update to authenticated
  using (exists (select 1 from public.orders o where o.id = order_id and o.seller_id = (select auth.uid())))
  with check (exists (select 1 from public.orders o where o.id = order_id and o.seller_id = (select auth.uid())));

create policy "Order parties read shipment events" on public.shipment_events for select to authenticated
  using (exists (select 1 from public.shipments s join public.orders o on o.id = s.order_id where s.id = shipment_id and (select auth.uid()) in (o.buyer_id, o.seller_id)));
create policy "Sellers create shipment events" on public.shipment_events for insert to authenticated
  with check (exists (select 1 from public.shipments s join public.orders o on o.id = s.order_id where s.id = shipment_id and o.seller_id = (select auth.uid())));

create policy "Order parties read delivery confirmation" on public.delivery_confirmations for select to authenticated
  using (exists (select 1 from public.orders o where o.id = order_id and (select auth.uid()) in (o.buyer_id, o.seller_id)));
create policy "Buyers confirm own delivery" on public.delivery_confirmations for insert to authenticated
  with check (buyer_id = (select auth.uid()) and exists (select 1 from public.orders o where o.id = order_id and o.buyer_id = (select auth.uid())));

create policy "Active boosts are public" on public.listing_boosts for select to anon, authenticated
  using ((status = 'active' and expires_at > now()) or seller_id = (select auth.uid()));
create policy "Sellers create boosts for own listings" on public.listing_boosts for insert to authenticated
  with check (seller_id = (select auth.uid()) and exists (select 1 from public.listings l where l.id = listing_id and l.seller_id = (select auth.uid())));
create policy "Sellers cancel pending boosts" on public.listing_boosts for update to authenticated
  using (seller_id = (select auth.uid()) and status = 'pending')
  with check (seller_id = (select auth.uid()) and status in ('pending', 'cancelled'));

grant select, insert on public.listing_reports to authenticated;
grant select, insert, update on public.shipments to authenticated;
grant select, insert on public.shipment_events, public.delivery_confirmations to authenticated;
grant select on public.listing_boosts to anon, authenticated;
grant insert, update on public.listing_boosts to authenticated;
grant usage, select on sequence public.shipment_events_id_seq to authenticated;

commit;
