begin;

create type public.listing_status as enum ('draft', 'active', 'reserved', 'sold', 'paused', 'rejected');
create type public.order_status as enum ('pending', 'paid', 'authentication', 'ready_to_ship', 'shipped', 'delivered', 'cancelled', 'refunded', 'disputed');
create type public.authenticity_status as enum ('pending', 'ai_review', 'manual_review', 'likely_authentic', 'inconclusive', 'rejected');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  full_name text,
  avatar_url text,
  bio text,
  city text,
  country_code text default 'XK',
  phone text,
  seller_verified boolean not null default false,
  identity_verified boolean not null default false,
  is_admin boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint profiles_username_format check (username is null or username ~ '^[a-z0-9._]{3,30}$')
);

create table public.categories (
  id bigint generated by default as identity primary key,
  parent_id bigint references public.categories(id) on delete set null,
  slug text not null unique,
  name_sq text not null,
  name_en text not null,
  is_active boolean not null default true,
  sort_order integer not null default 0
);

create table public.brands (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null unique,
  logo_url text,
  is_luxury boolean not null default false,
  is_active boolean not null default true
);

create table public.listings (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  category_id bigint references public.categories(id) on delete set null,
  brand_id bigint references public.brands(id) on delete set null,
  title text not null,
  description text not null default '',
  price numeric(12,2) not null check (price > 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  condition text not null,
  size text,
  color text,
  material text,
  gender text,
  city text,
  country_code text not null default 'XK',
  status public.listing_status not null default 'draft',
  authenticity_status public.authenticity_status not null default 'pending',
  negotiable boolean not null default true,
  shipping_available boolean not null default true,
  views_count bigint not null default 0,
  published_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.listing_images (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  storage_path text not null,
  sort_order integer not null default 0,
  width integer,
  height integer,
  created_at timestamptz not null default now(),
  unique (listing_id, storage_path)
);

create table public.favorites (
  user_id uuid not null references public.profiles(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, listing_id)
);

create table public.conversations (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid references public.listings(id) on delete set null,
  buyer_id uuid not null references public.profiles(id) on delete cascade,
  seller_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint conversations_distinct_users check (buyer_id <> seller_id),
  unique (listing_id, buyer_id, seller_id)
);

create table public.messages (
  id uuid primary key default gen_random_uuid(),
  conversation_id uuid not null references public.conversations(id) on delete cascade,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (length(body) between 1 and 5000),
  attachment_path text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table public.orders (
  id uuid primary key default gen_random_uuid(),
  buyer_id uuid not null references public.profiles(id) on delete restrict,
  seller_id uuid not null references public.profiles(id) on delete restrict,
  status public.order_status not null default 'pending',
  subtotal numeric(12,2) not null check (subtotal >= 0),
  shipping_amount numeric(12,2) not null default 0 check (shipping_amount >= 0),
  platform_fee numeric(12,2) not null default 0 check (platform_fee >= 0),
  total numeric(12,2) not null check (total >= 0),
  currency text not null default 'EUR' check (currency ~ '^[A-Z]{3}$'),
  shipping_address jsonb not null default '{}'::jsonb,
  payment_provider text,
  payment_reference text,
  tracking_number text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint orders_distinct_users check (buyer_id <> seller_id)
);

create table public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  listing_id uuid not null references public.listings(id) on delete restrict,
  title_snapshot text not null,
  price numeric(12,2) not null check (price > 0),
  quantity integer not null default 1 check (quantity = 1),
  unique (order_id, listing_id)
);

create table public.authenticity_checks (
  id uuid primary key default gen_random_uuid(),
  listing_id uuid not null references public.listings(id) on delete cascade,
  requested_by uuid not null references public.profiles(id) on delete cascade,
  status public.authenticity_status not null default 'pending',
  confidence numeric(5,2) check (confidence between 0 and 100),
  risk_flags jsonb not null default '[]'::jsonb,
  analysis jsonb not null default '{}'::jsonb,
  model text,
  reviewed_by uuid references public.profiles(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  type text not null,
  title text not null,
  body text not null default '',
  href text,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index listings_active_created_idx on public.listings (created_at desc) where status = 'active';
create index listings_seller_idx on public.listings (seller_id, created_at desc);
create index listings_category_idx on public.listings (category_id, created_at desc);
create index listings_brand_idx on public.listings (brand_id, created_at desc);
create index listing_images_listing_idx on public.listing_images (listing_id, sort_order);
create index conversations_buyer_idx on public.conversations (buyer_id, updated_at desc);
create index conversations_seller_idx on public.conversations (seller_id, updated_at desc);
create index messages_conversation_idx on public.messages (conversation_id, created_at);
create index orders_buyer_idx on public.orders (buyer_id, created_at desc);
create index orders_seller_idx on public.orders (seller_id, created_at desc);
create index notifications_user_idx on public.notifications (user_id, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger profiles_set_updated_at before update on public.profiles for each row execute function public.set_updated_at();
create trigger listings_set_updated_at before update on public.listings for each row execute function public.set_updated_at();
create trigger conversations_set_updated_at before update on public.conversations for each row execute function public.set_updated_at();
create trigger orders_set_updated_at before update on public.orders for each row execute function public.set_updated_at();
create trigger authenticity_checks_set_updated_at before update on public.authenticity_checks for each row execute function public.set_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, full_name, avatar_url)
  values (
    new.id,
    nullif(lower(regexp_replace(coalesce(new.raw_user_meta_data ->> 'username', ''), '[^a-z0-9._]', '', 'g')), ''),
    nullif(new.raw_user_meta_data ->> 'full_name', ''),
    nullif(new.raw_user_meta_data ->> 'avatar_url', '')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.categories enable row level security;
alter table public.brands enable row level security;
alter table public.listings enable row level security;
alter table public.listing_images enable row level security;
alter table public.favorites enable row level security;
alter table public.conversations enable row level security;
alter table public.messages enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.authenticity_checks enable row level security;
alter table public.notifications enable row level security;

create policy "Public profiles are readable" on public.profiles for select to anon, authenticated using (true);
create policy "Users update own profile" on public.profiles for update to authenticated
  using ((select auth.uid()) = id) with check ((select auth.uid()) = id and is_admin = false);

create policy "Categories are public" on public.categories for select to anon, authenticated using (is_active);
create policy "Brands are public" on public.brands for select to anon, authenticated using (is_active);

create policy "Active listings are public" on public.listings for select to anon, authenticated
  using (status = 'active' or seller_id = (select auth.uid()));
create policy "Sellers create own listings" on public.listings for insert to authenticated
  with check (seller_id = (select auth.uid()));
create policy "Sellers update own listings" on public.listings for update to authenticated
  using (seller_id = (select auth.uid())) with check (seller_id = (select auth.uid()));
create policy "Sellers delete own draft listings" on public.listings for delete to authenticated
  using (seller_id = (select auth.uid()) and status in ('draft', 'rejected'));

create policy "Images of visible listings are readable" on public.listing_images for select to anon, authenticated
  using (exists (select 1 from public.listings l where l.id = listing_id and (l.status = 'active' or l.seller_id = (select auth.uid()))));
create policy "Sellers manage listing images" on public.listing_images for all to authenticated
  using (exists (select 1 from public.listings l where l.id = listing_id and l.seller_id = (select auth.uid())))
  with check (exists (select 1 from public.listings l where l.id = listing_id and l.seller_id = (select auth.uid())));

create policy "Users read own favorites" on public.favorites for select to authenticated using (user_id = (select auth.uid()));
create policy "Users create own favorites" on public.favorites for insert to authenticated with check (user_id = (select auth.uid()));
create policy "Users delete own favorites" on public.favorites for delete to authenticated using (user_id = (select auth.uid()));

create policy "Participants read conversations" on public.conversations for select to authenticated
  using ((select auth.uid()) in (buyer_id, seller_id));
create policy "Buyers start conversations" on public.conversations for insert to authenticated
  with check (buyer_id = (select auth.uid()) and seller_id <> (select auth.uid()));
create policy "Participants update conversations" on public.conversations for update to authenticated
  using ((select auth.uid()) in (buyer_id, seller_id))
  with check ((select auth.uid()) in (buyer_id, seller_id));

create policy "Participants read messages" on public.messages for select to authenticated
  using (exists (select 1 from public.conversations c where c.id = conversation_id and (select auth.uid()) in (c.buyer_id, c.seller_id)));
create policy "Participants send messages" on public.messages for insert to authenticated
  with check (
    sender_id = (select auth.uid()) and
    exists (select 1 from public.conversations c where c.id = conversation_id and (select auth.uid()) in (c.buyer_id, c.seller_id))
  );
create policy "Recipients mark messages read" on public.messages for update to authenticated
  using (
    sender_id <> (select auth.uid()) and
    exists (select 1 from public.conversations c where c.id = conversation_id and (select auth.uid()) in (c.buyer_id, c.seller_id))
  )
  with check (sender_id <> (select auth.uid()));

create policy "Parties read orders" on public.orders for select to authenticated
  using ((select auth.uid()) in (buyer_id, seller_id));
create policy "Parties read order items" on public.order_items for select to authenticated
  using (exists (select 1 from public.orders o where o.id = order_id and (select auth.uid()) in (o.buyer_id, o.seller_id)));

create policy "Owners read authenticity checks" on public.authenticity_checks for select to authenticated
  using (
    requested_by = (select auth.uid()) or
    exists (select 1 from public.listings l where l.id = listing_id and l.seller_id = (select auth.uid()))
  );
create policy "Owners request authenticity checks" on public.authenticity_checks for insert to authenticated
  with check (
    requested_by = (select auth.uid()) and
    exists (select 1 from public.listings l where l.id = listing_id and l.seller_id = (select auth.uid()))
  );

create policy "Users read own notifications" on public.notifications for select to authenticated using (user_id = (select auth.uid()));
create policy "Users mark own notifications read" on public.notifications for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "Users delete own notifications" on public.notifications for delete to authenticated using (user_id = (select auth.uid()));

grant usage on schema public to anon, authenticated;
grant select on public.categories, public.brands to anon, authenticated;
grant select on public.profiles, public.listings, public.listing_images to anon, authenticated;
grant insert, update on public.profiles to authenticated;
grant insert, update, delete on public.listings, public.listing_images, public.favorites, public.conversations, public.messages to authenticated;
grant select on public.favorites, public.conversations, public.messages, public.orders, public.order_items, public.authenticity_checks, public.notifications to authenticated;
grant insert on public.authenticity_checks to authenticated;
grant update, delete on public.notifications to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into public.categories (slug, name_sq, name_en, sort_order) values
  ('women', 'Femra', 'Women', 10),
  ('men', 'Meshkuj', 'Men', 20),
  ('kids', 'Fëmijë', 'Kids', 30),
  ('bags', 'Çanta', 'Bags', 40),
  ('shoes', 'Këpucë', 'Shoes', 50),
  ('sneakers', 'Atlete', 'Sneakers', 60),
  ('watches', 'Ora', 'Watches', 70),
  ('jewelry', 'Bizhuteri', 'Jewelry', 80),
  ('sunglasses', 'Syze dielli', 'Sunglasses', 90),
  ('accessories', 'Aksesorë', 'Accessories', 100),
  ('beauty', 'Bukuri dhe parfume', 'Beauty & Perfume', 110),
  ('collectibles', 'Koleksione', 'Collectibles', 120);

insert into public.brands (slug, name, is_luxury) values
  ('balenciaga', 'Balenciaga', true),
  ('bottega-veneta', 'Bottega Veneta', true),
  ('burberry', 'Burberry', true),
  ('chanel', 'Chanel', true),
  ('dior', 'Dior', true),
  ('gucci', 'Gucci', true),
  ('hermes', 'Hermès', true),
  ('louis-vuitton', 'Louis Vuitton', true),
  ('moncler', 'Moncler', true),
  ('prada', 'Prada', true),
  ('rolex', 'Rolex', true),
  ('saint-laurent', 'Saint Laurent', true);

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('avatars', 'avatars', true, 5242880, array['image/jpeg','image/png','image/webp']),
  ('listing-images', 'listing-images', true, 10485760, array['image/jpeg','image/png','image/webp']),
  ('authenticity-evidence', 'authenticity-evidence', false, 10485760, array['image/jpeg','image/png','image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

create policy "Public avatar files" on storage.objects for select to anon, authenticated using (bucket_id = 'avatars');
create policy "Users upload own avatar" on storage.objects for insert to authenticated
  with check (bucket_id = 'avatars' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "Users update own avatar" on storage.objects for update to authenticated
  using (bucket_id = 'avatars' and owner_id = (select auth.uid()::text))
  with check (bucket_id = 'avatars' and owner_id = (select auth.uid()::text));
create policy "Users delete own avatar" on storage.objects for delete to authenticated
  using (bucket_id = 'avatars' and owner_id = (select auth.uid()::text));

create policy "Public listing files" on storage.objects for select to anon, authenticated using (bucket_id = 'listing-images');
create policy "Users upload own listing files" on storage.objects for insert to authenticated
  with check (bucket_id = 'listing-images' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "Users update own listing files" on storage.objects for update to authenticated
  using (bucket_id = 'listing-images' and owner_id = (select auth.uid()::text))
  with check (bucket_id = 'listing-images' and owner_id = (select auth.uid()::text));
create policy "Users delete own listing files" on storage.objects for delete to authenticated
  using (bucket_id = 'listing-images' and owner_id = (select auth.uid()::text));

create policy "Users upload own authenticity evidence" on storage.objects for insert to authenticated
  with check (bucket_id = 'authenticity-evidence' and (storage.foldername(name))[1] = (select auth.uid())::text);
create policy "Users read own authenticity evidence" on storage.objects for select to authenticated
  using (bucket_id = 'authenticity-evidence' and owner_id = (select auth.uid()::text));
create policy "Users delete own authenticity evidence" on storage.objects for delete to authenticated
  using (bucket_id = 'authenticity-evidence' and owner_id = (select auth.uid()::text));

commit;
